# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 15:25
from __future__ import unicode_literals
import re
from django.db import migrations


def migrate_email(apps, schema_editor):
    FOIARequest = apps.get_mdels('foia', 'request')
    Address = apps.get_model('communication', 'Address')
    EmailAddress = apps.get_model('communication', 'EmailAddress')
    PhoneNumber = apps.get_model('communication', 'PhoneNumber')
    email_separator_re = re.compile(r'[^\w\.\-\+\&@_]+')

    for foia in FOIARequest.objects.all():
        if foia.old_email:
            if '@' in foia.old_email:
                email_addr = EmailAddress.objects.fetch(foia.old_email)
                foia.email = email_addr
                foia.save()
            elif foia.old_email.isdigit() and 10 <= len(foia.old_email) <= 11:
                phone = PhoneNumber.objects.get_or_create(
                        number=foia.old_email,
                        type='fax',
                        )
                foia.fax = phone
                foia.save()
            else:
                print('What is this?: %s' % foia.old_email)
        if foia.other_emails:
            for email in email_separator_re.split(foia.other_emails):
                email_addr = EmailAddress.objects.fetch(email)
                foia.cc_emails.add(email_addr)





class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0037_auto_20171004_1353'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_email, lambda a, s: None),
    ]
